// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Locomotiv.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251122064156_AddElementTable")]
    partial class AddElementTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Locomotiv.Model.ArretItineraire", b =>
                {
                    b.Property<int>("IdArret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DureeArret")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HeureArrivee")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HeureDepart")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdItineraire")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdPointInteret")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdStation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordre")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PointInteretId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StationIdStation")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdArret");

                    b.HasIndex("IdItineraire");

                    b.HasIndex("PointInteretId");

                    b.HasIndex("StationIdStation");

                    b.ToTable("ArretsItineraire");
                });

            modelBuilder.Entity("Locomotiv.Model.Block", b =>
                {
                    b.Property<int>("IdBlock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EtatSignal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItineraireIdItineraire")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LatitudeDebut")
                        .HasColumnType("REAL");

                    b.Property<double>("LatitudeFin")
                        .HasColumnType("REAL");

                    b.Property<double>("LongitudeDebut")
                        .HasColumnType("REAL");

                    b.Property<double>("LongitudeFin")
                        .HasColumnType("REAL");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrainOccupantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdBlock");

                    b.HasIndex("ItineraireIdItineraire");

                    b.HasIndex("TrainOccupantId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("Locomotiv.Model.Itineraire", b =>
                {
                    b.Property<int>("IdItineraire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HeureArriveeEstimee")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HeureDepart")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdTrain")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdItineraire");

                    b.HasIndex("IdTrain");

                    b.ToTable("Itineraires");
                });

            modelBuilder.Entity("Locomotiv.Model.PointInteret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PointsInteret");
                });

            modelBuilder.Entity("Locomotiv.Model.Signal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BlockAssocieIdBlock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EtatSignal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdBlockAssocie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdStation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlockAssocieIdBlock");

                    b.HasIndex("IdStation");

                    b.ToTable("Signals");
                });

            modelBuilder.Entity("Locomotiv.Model.Station", b =>
                {
                    b.Property<int>("IdStation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapaciteMax")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .HasColumnType("TEXT");

                    b.HasKey("IdStation");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Locomotiv.Model.Train", b =>
                {
                    b.Property<int>("IdTrain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstEnGare")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Etat")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HeureArrivee")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HeureDepart")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdStation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Locomotive")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NombreWagons")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdTrain");

                    b.HasIndex("IdStation");

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("Locomotiv.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Locomotiv.Model.Voie", b =>
                {
                    b.Property<int>("IdVoie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstOccupee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdStation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdTrainActuel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrainActuelIdTrain")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdVoie");

                    b.HasIndex("IdStation");

                    b.HasIndex("TrainActuelIdTrain");

                    b.ToTable("Voies");
                });

            modelBuilder.Entity("Locomotiv.Model.ArretItineraire", b =>
                {
                    b.HasOne("Locomotiv.Model.Itineraire", "Itineraire")
                        .WithMany("Arrets")
                        .HasForeignKey("IdItineraire")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Locomotiv.Model.PointInteret", "PointInteret")
                        .WithMany()
                        .HasForeignKey("PointInteretId");

                    b.HasOne("Locomotiv.Model.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationIdStation");

                    b.Navigation("Itineraire");

                    b.Navigation("PointInteret");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Locomotiv.Model.Block", b =>
                {
                    b.HasOne("Locomotiv.Model.Itineraire", null)
                        .WithMany("BlocksTraverses")
                        .HasForeignKey("ItineraireIdItineraire");

                    b.HasOne("Locomotiv.Model.Train", "TrainOccupant")
                        .WithMany()
                        .HasForeignKey("TrainOccupantId");

                    b.Navigation("TrainOccupant");
                });

            modelBuilder.Entity("Locomotiv.Model.Itineraire", b =>
                {
                    b.HasOne("Locomotiv.Model.Train", "Train")
                        .WithMany()
                        .HasForeignKey("IdTrain")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Locomotiv.Model.Signal", b =>
                {
                    b.HasOne("Locomotiv.Model.Block", "BlockAssocie")
                        .WithMany()
                        .HasForeignKey("BlockAssocieIdBlock");

                    b.HasOne("Locomotiv.Model.Station", "Station")
                        .WithMany("Signaux")
                        .HasForeignKey("IdStation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockAssocie");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Locomotiv.Model.Train", b =>
                {
                    b.HasOne("Locomotiv.Model.Station", "Station")
                        .WithMany("Trains")
                        .HasForeignKey("IdStation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Locomotiv.Model.User", b =>
                {
                    b.HasOne("Locomotiv.Model.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Locomotiv.Model.Voie", b =>
                {
                    b.HasOne("Locomotiv.Model.Station", "Station")
                        .WithMany("Voies")
                        .HasForeignKey("IdStation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Locomotiv.Model.Train", "TrainActuel")
                        .WithMany()
                        .HasForeignKey("TrainActuelIdTrain");

                    b.Navigation("Station");

                    b.Navigation("TrainActuel");
                });

            modelBuilder.Entity("Locomotiv.Model.Itineraire", b =>
                {
                    b.Navigation("Arrets");

                    b.Navigation("BlocksTraverses");
                });

            modelBuilder.Entity("Locomotiv.Model.Station", b =>
                {
                    b.Navigation("Signaux");

                    b.Navigation("Trains");

                    b.Navigation("Voies");
                });
#pragma warning restore 612, 618
        }
    }
}
